---
title: "PDCL : Define Optimal Parameters"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
# Load required libraries (others are load directly in sourced files)
library(Biobase)
library(dplyr)
library(purrr)
library(plotly)
library(DT)
library(mclust)
library(factoextra)
library(penda)
library(DESeq2)

# Source files with functions used in next steps
source("~/PhD/Project/PDCL/Code/R/pdcl-dataset.R")
source("~/PhD/Project/PDCL/Code/R/gprofiler-analysis.R")
source("~/PhD/Project/PDCL/Code/R/process-result.R")
source("~/PhD/Project/PDCL/Code/R/quickgo.R")
source("~/PhD/Project/PDCL/Code/R/kegg.R")
source("~/PhD/Project/PDCL/Code/R/reactome.R")

validation_datasets_param <- list(
  nb_validation_run = 10,
  nb_validation_ctrl = 2
)
penda_datasets_param <- list(
  detectlowvalue = T, 
  detectNA = T, 
  threshold = 0.99
)
penda_simu_param <- list(
  size_grp = 100,
  quant_simu = 0.05
)
penda_L_H_params <- list(
  threshold = 0.99, 
  s_max = 100
)
penda_quantile_param <- list(
  quantile_values = seq(0, 1, by = 0.05),
  factor_values = seq(1, 2, by = 0.1),
  FDR_max = 0.05
)
penda_threshold_param <- list(
  threshold_values = c(0.01, seq(0.05, 1.2, by = 0.05)),
  iterations = 10
)
rerun_cache <- T 
result_dir = "Result_pdcl_define_optim_param/"
```

# Prepare data

```{r prepare-count-data}
control_count_data <- read.table(PDCL_DATASET_PARAM$control_count_path, header = T, sep = "\t", as.is = c("id", "symbol") )
control_count_data <- control_count_data[, colnames(control_count_data) %in% c("id", "symbol", PDCL_DATASET_PARAM$control_sample_names)]
pdcl_count_data <- read.table(PDCL_DATASET_PARAM$pdcl_count_path, sep = "\t", header = T, as.is = "gene_id", check.names = F)

# Merge control and PDCL counts into one dataframe
count_data <- merge(control_count_data, pdcl_count_data, by.x = "symbol", by.y = "gene_id")

# Associate each row with a gene symbol
row.names(count_data) <- count_data$symbol

# Remove symbol and id columns
count_data <- count_data %>% dplyr::select(!c(symbol, id))
condition_vect <- c(
  rep("control", length(PDCL_DATASET_PARAM$control_sample_names)), 
  rep("pdcl", length(PDCL_DATASET_PARAM$pdcl_sample_names))
)
sample <- gsub("^(.*)_(Br\\d.*)", "\\1", colnames(count_data), ignore.case = T, perl = T, fixed = F)
replicate <- gsub("^(.*)_(Br\\d.*)", "\\2", colnames(count_data), ignore.case = T, perl = T, fixed = F)
count_metadata <- data.frame(
  sample = as.factor(sample),
  replicate = as.factor(replicate),
  condition = as.factor(condition_vect),
  row.names = colnames(count_data)
)
```

```{r make-data}
dds <- DESeqDataSetFromMatrix(
  countData = count_data, 
  colData = count_metadata, 
  design = ~condition
)
dds <- DESeq(dds)
pld <- normTransform(dds)
normalized_count <- assay(pld, blind = F)
control_index <- which(count_metadata$condition == "control")
control_names <- colnames(normalized_count)[control_index]
all_data <- as.matrix(normalized_count)
```

Here we prepare several PenDA datasets to perform crossed-validation.
We don't have enough controls so we use this approach to ensure the quality of the Differential Expression analysis.

```{r make-penda-datasets}
simulated_cases <- lapply(control_names, function(x){x})

all_penda_datasets <- xfun::cache_rds({
  with(penda_datasets_param, {
    lapply(1:length(simulated_cases), function(i){
      data_simu <- simulated_cases[[i]]
      names_ctrl_set <- control_names[!(control_names %in% data_simu)]
      index_ctrl_set <- which(colnames(all_data) %in% names_ctrl_set)
      cases <- all_data[,-control_index]
      ctrl <- all_data[,index_ctrl_set]
      penda::make_dataset(ctrl, cases, detectlowvalue = T, detectNA = T, threshold = 0.99)
    })
  })
}, rerun = rerun_cache, file = "all_penda_datasets.rds", dir = result_dir)

all_simulated_datasets <- xfun::cache_rds({
  lapply(1:length(simulated_cases), function(i){
      data_simu <- simulated_cases[[i]]
      data_ctrl <- all_penda_datasets[[i]]$data_ctrl
      all_data[row.names(data_ctrl),data_simu]
    })
}, rerun = rerun_cache, file = "all_penda_simulated_datasets.rds", dir = result_dir)
```

```{r compute-L-H-lists}
all_L_H_list <- with(penda_L_H_params, {
  lapply(all_penda_datasets, function(penda_dataset){
    penda::compute_lower_and_higher_lists(penda_dataset$data_ctrl, threshold = threshold, s_max = s_max)
  })
})
```

```{r generate-simulatd-datasets}
all_simulation <- xfun::cache_rds({
  with(penda_simu_param, {
    lapply(1:length(all_simulated_datasets), function(i){
      data_ctrl <- all_penda_datasets[[i]]$data_ctrl
      data_cases <- all_penda_datasets[[i]]$data_case
      data_simu <- all_simulated_datasets[[i]]
      penda::complex_simulation(data_ctrl, data_cases, data_simu, size_grp, quant_simu)
    })
  })
}, rerun = rerun_cache, file = "all_simulation.rds", dir = result_dir)
```

# Find Optimal Quantiles

```{r choose-quantiles, results='hide'}
all_which_quantiles <- xfun::cache_rds({
  with(penda_quantile_param, {
    lapply(1:length(all_simulation), function(i){
      data_ctrl <- all_penda_datasets[[i]]$data_ctrl
      data_cases <- all_penda_datasets[[i]]$data_case
      data_simu <- all_simulation[[i]]
      penda::choose_quantile(data_ctrl, data_simu, factor_values = factor_values, quantile_values = quantile_values)
    })
  })
}, rerun = rerun_cache, file = "all_which_quantiles.rds", dir = result_dir)
```

```{r optimal-quantiles}
all_best_quantile <- with(penda_quantile_param, {
   lapply(all_which_quantiles, function(which_quantile){
     penda::select_quantile_param(which_quantile, FDR_max = FDR_max)
   })
})
df_quant <- purrr::imap_dfr(all_which_quantiles, function(which_quantile, simu_nb){
  data.frame(
    factor = factor(which_quantile[,1]),
    quantile = factor(which_quantile[,2]),
    FDR = which_quantile[,3],
    TPR = which_quantile[,4],
    simu_dataset = simu_nb
  )
})

df_best_quantile <- purrr::imap_dfr(all_best_quantile, function(best_quantile, i){
  data.frame(factor = best_quantile$factor, quantile = best_quantile$quantile, FDR = best_quantile$FDR, TPR = best_quantile$TPR, simu_dataset = i, row.names = NULL)
})
df_best_quantile
```


```{r plot-optimal-quantiles, echo = FALSE}
best_quantile <- df_best_quantile[which.min(df_best_quantile$FDR),]

plot_optimal_quantiles <- ggplot(df_quant, aes(x = FDR, y = TPR, color = quantile, group = factor, shape = factor)) + geom_point() + 
  geom_line() + theme_minimal() +
  geom_vline(xintercept = best_quantile$FDR, linetype = "dotted")  +
  geom_hline(yintercept = best_quantile$TPR, linetype = "dotted")

plot_optimal_quantiles
```

# Find Optimal Threshold

```{r choose-thresholds, results='hide'}
all_which_threshold <- xfun::cache_rds({
  with(penda_threshold_param,{
    lapply(1:length(all_best_quantile), function(i){
      data_ctrl <- all_penda_datasets[[i]]$data_ctrl
      best_quant <- all_best_quantile[[i]]
      L_H_list <- all_L_H_list[[i]]
      simulation <- all_simulation[[i]]
      best_quant = best_quantile$quantile
      best_fact = best_quantile$factor
      penda::choose_threshold(data_ctrl, L_H_list, iterations, simulation, threshold_values, quant_test = best_quant, factor_test = best_fact)
    })
  })
}, rerun = rerun_cache, file = "all_which_threshold.rds", dir = result_dir)

```

```{r optimal-thresholds, message=FALSE}
all_best_threshold <- lapply(all_which_threshold, function(which_threshold){
  penda::select_threshold_param(which_threshold, FDR_max = 0.05)
})

df_which_threshold <- purrr::imap_dfr(all_which_threshold, function(which_threshold, i){
  which_threshold = apply(which_threshold, 2, as.numeric)
  if(length(unique(which_threshold[,1])) > 1){
    results_threshold = c()
    for(value in unique(which_threshold[,2])){
      sum_value = colSums(which_threshold[which_threshold[,"threshold"] == value, ])
      results_threshold = rbind(results_threshold, c(value, sum_value[c(6, 7, 8, 9)]))
    }
  } else {
    results_threshold = which_threshold[, c(2, 6, 7, 8, 9)]
  }
  
  df = data.frame(threshold = as.factor(results_threshold[,1]),
                  FDR = results_threshold[,"FP"] / (results_threshold[,"TP"] + results_threshold[,"FP"]), 
                  TPR  = results_threshold[,"TP"] / (results_threshold[,"TP"] + results_threshold[,"FN"]),
                  simu_datasets = i)
})

df_best_threshold <- purrr::imap_dfr(all_best_threshold, function(best_threshold, i){
  data.frame(
    threshold = best_threshold$threshold,
    FDR = best_threshold$FDR,
    TPR = best_threshold$TPR,
    FPR = best_threshold$FPR,
    simu_dataset = i, 
    row.names = NULL
  )
})
df_best_threshold
```

```{r plot-optimal-thresholds, echo=FALSE}
best_threshold <- df_best_threshold[which.min(df_best_threshold$FDR), ]
  
plot_optimal_thresholds <- ggplot(df_which_threshold, aes(x = FDR, y = TPR, color = threshold, group = simu_datasets)) +
  geom_point() + geom_line() + theme_minimal() +
  geom_vline(xintercept = best_threshold$FDR, linetype = "dotted")  +
  geom_hline(yintercept = best_threshold$TPR, linetype = "dotted")   
plot_optimal_thresholds
```

# Parameter Values
```{r print-param}
validation_datasets_param
penda_datasets_param
penda_simu_param
penda_L_H_params
penda_quantile_param
penda_threshold_param
rerun_cache
result_dir
```

```{r save-image, include=FALSE}
save.image("pdcl_define_optim_param.RData")
```
